version: '3'
services:
  trezor-user-env-unix:
    container_name: trezor-user-env.unix
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    network_mode: "host"
    ports:
      - "9001:9001"
    environment:
      - DISPLAY=:0

  trezor-user-env-mac:
    container_name: trezor-user-env.mac
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    ports:
      - "9001:9001"
    environment:
      - DISPLAY=docker.for.mac.host.internal:0
