version: '2'
services:
  trezor-user-env-nix:
    container_name: trezor-user-env-nix
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    ports:
      - "9001:9001"
    environment:
      - DISPLAY=docker.for.mac.host.internal:0
